name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint & run tests
    steps:
      - uses: actions/checkout@v1
      - name: Install test tools
        run: sudo apt-get install -y bats shellcheck
      - name: Lint
        run: make lint
      - name: Install dokku
        run: |
          wget https://raw.githubusercontent.com/dokku/dokku/v0.22.0/bootstrap.sh
          sudo DOKKU_TAG=v0.22.0 bash bootstrap.sh
      - name: Install discourse plugin
        run: |
          sudo dokku plugin:install file:///$(pwd) discourse
      - name: Run tests
        run: sudo make test
